name: Remote SSH
on:
  push:
    branches:
        - production

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IP }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd programming/VPlan_FR/
          
          kill -INT (lsof -t nohup.out)
          
          git checkout production
          git pull
          source venv/bin/activate.fish
          pip install -r requirements.txt
          
          rm nohup.out
          nohup venv/bin/python3 -m backend.load_plans --ignore-exceptions --never-raise-out-of-proxies -l 8 &
          disown (lsof -t nohup.out)
          
          cd client
          npm install --force
          npm run build
          
          sudo service apache2 restart
